GET https://example.com/comments/1 HTTP/1.1

###

GET http://localhost:8000/api/ai/reply?message=Hello3 HTTP/1.1

###

POST http://localhost:8000/auth/register HTTP/1.1
content-type: application/json

{
    "count": 10
}

###

POST http://localhost:8000/api/ai/chat HTTP/1.1
content-type: application/json

{
    "message": "Show me how can i improve my code?"
}